# create service of load balancer for app in deployment.yaml file labeled "example app"

apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-app
spec:
  type: LoadBalancer
  selector:
    app: example-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
# create endpoints (port 80 to accept traffic, 5000 is target port ot accept container at) to service based on this label

# 1. init service.yaml to create the labeled service with specificied endpoints -> kubectl apply -f .\services\service.yaml
# 2. check if service is up and running -> kubectl get service
# 3. check to see if service endpoints are set -> kubectl describe <service_name>
